package com.mytiki.sdk.capture.receipt.capacitor

import com.microblink.linking.*

enum class RetailerEnum (val value: Int){
walmart_ca(WALMART_CA),
staples_ca(STAPLES_CA),
seamless(SEAMLESS),
drizly(DRIZLY),
target(TARGET),
costco(COSTCO),
kroger(KROGER),
safeway(SAFEWAY),
acme_markets(ACME_MARKETS),
albertsons(ALBERTSONS),
jewel_osco(JEWEL_OSCO),
food_4_less(FOOD_4_LESS),
harris_teeter(HARRIS_TEETER),
ralphs(RALPHS),
fred_meyer(FRED_MEYER),
vons(VONS),
publix(PUBLIX),
walgreens(WALGREENS),
walmart(WALMART),
wegmans(WEGMANS),
instacart(INSTACART),
starbucks(STARBUCKS),
shipt(SHIPT),
cvs(CVS),
home_depot(HOME_DEPOT),
lowes(LOWES),
meijer(MEIJER),
shoprite(SHOPRITE),
sephora(SEPHORA),
bestbuy(BESTBUY),
kohls(KOHLS),
chewy(CHEWY),
staples(STAPLES),
macys(MACYS),
grubhub(GRUBHUB),
dollar_general(DOLLAR_GENERAL),
dollar_tree(DOLLAR_TREE),
sams_club(SAMS_CLUB),
food_lion(FOOD_LION),
family_dollar(FAMILY_DOLLAR),
dominos_pizza(DOMINOS_PIZZA),
taco_bell(TACO_BELL),
door_dash(DOOR_DASH),
heb(HEB),
bjs_wholesale(BJS_WHOLESALE),
hyvee(HYVEE),
rite_aid(RITE_AID),
giant_eagle(GIANT_EAGLE),
marshalls(MARSHALLS),
tj_maxx(TJ_MAXX),
bed_bath_and_beyond(BED_BATH_AND_BEYOND),
dicks_sporting_goods(DICKS_SPORTING_GOODS),
nike(NIKE),
amazon_beta(AMAZON_BETA),
amazon_uk_beta(AMAZON_UK_BETA),
amazon_ca_beta(AMAZON_CA_BETA),
uber_eats(UBER_EATS),
gap(GAP),
sprouts(SPROUTS),
ulta(ULTA);

}
