require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

source 'https://github.com/BlinkReceipt/PodSpecRepo.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'MytikiTikiCaptureReceiptCapacitor', :path => '../../..'
end

target 'App' do
  capacitor_pods
  use_frameworks!

  pod 'BlinkReceipt', '~> 1.38'
  pod 'BlinkEReceipt', '~> 2.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
