source 'https://github.com/BlinkReceipt/PodSpecRepo.git' # <- add this
source 'https://cdn.cocoapods.org/' # <- add this

platform :ios, '13.0'

def capacitor_pods
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin'do
  capacitor_pods
  use_frameworks!
  
  pod 'BlinkReceipt', '~> 1.27' # <- add this
  pod 'BlinkEReceipt', '~> 2.0' # <- add this
end


target 'PluginTests' do
  capacitor_pods
end
